ERP:
    url: "https://staging-spc.ecustomerportal.com/web/site/login"
    # username: aruni.j@algospring.com
    # Password: spc1234

    username: aruni.j@algospring.com
    password: Spc@1234

    # username: bot2@spcfz.ae
    # password: spc1234






    
sleep:
  max: 4  
  min: 1  
  



data_path:
  Base: "C:/my works/SPC_VISA_PROCESS/SPC_-VISA-PROCESS-_RPA_SYSTEM/data/"
  Database: "C:/my works/SPC_VISA_PROCESS/SPC_-VISA-PROCESS-_RPA_SYSTEM/database/"
  Auth: "C:/my works/SPC_VISA_PROCESS/SPC_-VISA-PROCESS-_RPA_SYSTEM/src/pages/Zoho/auth/"
